@baseUrl = http://localhost:3000

@contentType = application/json

@accessToken = {{login.response.body.$.accessToken}}

# @categoryId = {{createCategory.response.body.$.id}}

@categoryId = 5f9e3089-a45a-4857-a9c4-463427a0a464

@mediaId = {{createMedia.response.body.$.id}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "john123123@example.com",
    "password": "Password123!"
}

### Create category
# @name createCategory
POST {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "New categoria",
    "icon": "book"   
}

### Create a new Media
# @name createMedia
POST {{baseUrl}}/media
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "title": "Test Media 3",
    "comment": "This is a test media item.",
    "progress": 50,
    "availableIn": "Netlix",
    "genre": "Fiction",
    "categoryId": "{{categoryId}}"
}

### Update Media by id
PATCH {{baseUrl}}/media/{{mediaId}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "title": "Teste - Updated",
    "comment": "An updated comment for the classic novel.",
    "availableIn": "Amazon Prime",
    "genre": "Classic Fiction",
    "categoryId": "{{categoryId}}"
}

### Get all users
GET {{baseUrl}}/media
Authorization: Bearer {{accessToken}}

### Get user by id
GET {{baseUrl}}/media/{{mediaId}}
Authorization: Bearer {{accessToken}}

### Delete Media by id
DELETE {{baseUrl}}/media/{{mediaId}}
Authorization: Bearer {{accessToken}}