@baseUrl = http://localhost:3000

@contentType = application/json

@accessToken = {{login.response.body.$.accessToken}}

# @categoryId = {{createCategory.response.body.$.id}}

@categoryId = 5f9e3089-a45a-4857-a9c4-463427a0a464

@mediaId = {{createMedia.response.body.$.id}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "john123123@example.com",
    "password": "Password123!"
}

### Create a new Media
# @name createMedia
POST {{baseUrl}}/media
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "title": "Test Media28363333",
    "comment": "This is a test media item.",
    "currentProgress": 50,
    "totalProgress": 100,
    "status": "IN_PROGRESS",
    "availableIn": ["Netflix", "Amazon Prime"],
    "genre": "Fiction",
    "categoryId": "{{categoryId}}"
}

### Update Media by id
PATCH {{baseUrl}}/media/f07e2bc8-4b2b-41b2-9d08-e919c2c53d19
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "currentProgress": 10,
    "totalProgress": 100
}

### Update Media status by id
PATCH {{baseUrl}}/media/f07e2bc8-4b2b-41b2-9d08-e919c2c53d19
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "status": "IN_PROGRESS"
}

### Get all users
GET {{baseUrl}}/media
Authorization: Bearer {{accessToken}}

### Get historical media for a user
GET {{baseUrl}}/media/historical
Authorization: Bearer {{accessToken}}

### Get user by id
GET {{baseUrl}}/media/{{mediaId}}
Authorization: Bearer {{accessToken}}

### Get media by category
GET {{baseUrl}}/media/category/d54313aa-0668-4288-b070-2634b7cf8d0a
Authorization: Bearer {{accessToken}}

### Get media by category
GET {{baseUrl}}/media/category/{{categoryId}}
Authorization: Bearer {{accessToken}}

### Delete Media by id
DELETE {{baseUrl}}/media/{{mediaId}}
Authorization: Bearer {{accessToken}}