@baseUrl = http://localhost:3000

@contentType = application/json

@accessToken = {{login.response.body.$.accessToken}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "john123123@example.com",
    "password": "Password123!"
}

### Create category
POST {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Books",
    "icon": "book"
    
}

### Get all categories
GET {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}

### Get category by id
GET {{baseUrl}}/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}

### Delete Category by id
DELETE {{baseUrl}}/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}