@baseUrl = http://localhost:3000

@contentType = application/json

@accessToken = {{login.response.body.$.accessToken}}

@categoryId = {{createCategory.response.body.$.id}}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "john123123@example.com",
    "password": "Password123!"
}

### Create category
# @name createCategory
POST {{baseUrl}}/categories
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Testee",
    "icon": "book"
    
}

### Get all categories
GET {{baseUrl}}/categories
Authorization: Bearer {{accessToken}}

### Get category by id
GET {{baseUrl}}/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}

### Update Category by id
PATCH {{baseUrl}}/categories/{{categoryId}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Updated Category Name",
    "icon": "updated-icon"
}

### Delete Category by id
DELETE {{baseUrl}}/categories/{{categoryId}}
Authorization: Bearer {{accessToken}}